#!/usr/bin/python
import datetime
import os
import sys
t1 = datetime.datetime.now()
os.system("java -cp ../bin:../other/jsqlparser.jar edu.buffalo.cse562.Main --data /../data /../sqlfile/"+sys.argv[1]+" > "+sys.argv[1]+".dat")
t2 = datetime.datetime.now()
diff = t2-t1
print diff
print diff.seconds
print diff.microseconds


